pods:

- name: pod-alpha
  containerName: alpha-container
  image: nginx:1.25
  containerPort: 80

- name: pod-beta
  containerName: beta-container
  image: busybox:latest
  command:
  - /bin/sh
  - -c
  - echo 'Hello from Pod Beta'; sleep 3600

- name: pod-gamma
  containerName: gamma-container
  image: httpd:2.4
  containerPort: 80

services:

- name: service-alpha
  type: ClusterIP
  port: 8080
  targetPort: 80
  selector:
    pod-spec-name: pod-alpha

- name: service-gamma
  type: NodePort
  port: 80
  targetPort: 80
  selector:
    pod-spec-name: pod-gamma

- name: service-all-pods
  type: ClusterIP
  port: 9000
  targetPort: 80
  selector:
    app: multi-pod-chart
